"""Parameters file"""
# Input file
image_path = 'Images/SaturationTest.jpg'

# False Contour Params
CONTOUR_AREA_THRESH = 500
DILATION_ITERATIONS = 3
DILATION_KERNEL_SIZE = (5, 5)
GABOR_KERNEL_SIZE = (5, 5)
GAUSS_SIZE = 100
GUESSES_THRESHOLD = 50
GAUSSIAN_PARAMS_BOX_SIZE = 5
POST_GABOR_THRESHOLD = 127
THETAS_STEP = 10
PAD_SIZE = 300
DRAW_THICKNESS = 2
DIFFUSION_OVERLAY = 0.2
IS_GRAY = False
SAVE = True
SAVE_ONCE = True

# Diffusion Params

