# Main params
image_path = 'Images/neon_01.png'

# False Contour Params
CONTOUR_AREA_THRESH = 500
DILATION_ITERATIONS = 3
DILATION_KERNEL_SIZE = (5, 5)
GABOR_KERNEL_SIZE = (5, 5)
GAUSS_SIZE = 71
GUESSES_THRESHOLD = 30
GAUSSIAN_PARAMS_BOX_SIZE = 5
POST_GABOR_THRESHOLD = 127
THETAS_STEP = 5

# Diffusion Params

