# Main params
image_path = 'Images/neon_31.png'

# False Contour Params
CONTOUR_AREA_THRESH = 500
DILATION_ITERATIONS = 3
DILATION_KERNEL_SIZE = (3, 3)
GABOR_KERNEL_SIZE = (5, 5)
GAUSS_SIZE = 25
GUESSES_THRESHOLD = 60
GAUSSIAN_PARAMS_BOX_SIZE = 5
POST_GABOR_THRESHOLD = 170
THETAS_STEP = 30
PAD_SIZE = 300
DRAW_THICKNESS = 1
IS_GRAY = False
SAVE = True
SAVE_ONCE = True

# Diffusion Params

